title:              Defense Against The Dark Arts
email:              wuyo@oregonstate.edu
description:        A Blog for CS 373
author:             Yonghao Wu
baseurl:            "/"
url:                "https://wuyo.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    wuyo
# facebook_username:  StartBootstrap
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
